env:
  global:
  - CC_TEST_REPORTER_ID=11204d37f66a611021f5b19b4ed934af452f1998edad215126b1ee7e4388bff6
before_install:
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
language: ruby
rvm:
- 2.6.5
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rails test
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
after_success:
  - openssl aes-256-cbc -K $encrypted_be75e374e0ff_key -iv $encrypted_be75e374e0ff_iv -in id_rsa.enc -out ~/.ssh/id_rsa.pub -d
  - "bundle exec cap production deploy"
